import { randomUUID } from "node:crypto";
import pg from "pg";
import { Db, loadEnv, ensureScope } from "@veritymem/ledger";
const env = loadEnv();
const db = new Db({ connectionString: env.databaseUrl, max: 1, applicationName: "probe-scope" });
const exec = { query: (t: string, p?: readonly unknown[]) => db.systemQuery(t, p ?? []) };
const t = randomUUID();
console.log("asking for tenant:", t);
const s = await ensureScope(exec, { tenant: t, project: "p", purpose: ["pp"] });
console.log("ensureScope returned:", JSON.stringify(s));
const owner = new pg.Client({ connectionString: "postgres://verity:verity@127.0.0.1:55432/veritymem" });
await owner.connect();
console.log("stored row:", (await owner.query("SELECT tenant_id, scope_id, project FROM scopes WHERE scope_id=$1::uuid", [s.scope_id])).rows);
console.log("rows with my tenant:", (await owner.query("SELECT count(*)::int n FROM scopes WHERE tenant_id=$1::uuid", [t])).rows);
await owner.end();
await db.close();
